//***************************************************************************
// Copyright (c) 2026 for information on the respective copyright owner
// see the NOTICE file and/or the following repository:
//     https://github.com/boschglobal/automotive-bus-schema
//
// SPDX-License-Identifier: Apache-2.0
//***************************************************************************

namespace AutomotiveBus.Diagnostic.ServiceRpc;


/**
    IDL for Automotive Bus - Diagnostic Interface - Service RPC
    ===========================================================

    Service RPC

    MIME Type : application/x-automotive-bus; interface=diagnostic; type=srpc; schema=fbs
    Flatbuffers file identifier : DSRP


    Generic RPC interface for dispatching a function on a named service.
*/


table MessageContext {
    /// Request: Container for the request content.
    request: [ubyte];
    /// Response: Container for the response content.
    response: [ubyte];

    /// Request: Type of request (transparent to the Service RPC).
    request_type: ubyte;
    /// Request: Source of request (transparent to the Service RPC).
    request_source: ubyte;

    /// Response: Include the request bytes in the response message.
    response_include_request: bool;
    /// Response: A response is returned in all cases, or only when an error has occurred."
    response_required: bool = true;

    /// Metadata: An identifier for this message context.
    context_id: ubyte;
    /// Metadata: Frame identifier when the response should be associated with a network pdu.
    rx_pdu_id: byte;
}

table InvokeCall {
    service: string (required);
    function: string (required);
    op_status: ubyte;
    ctx: MessageContext (required);
}

table InvokeReturn {
    return_value: ubyte;
    error_code: ubyte;
    ctx: MessageContext (required);
}

union Payload {
    InvokeCall,
    InvokeReturn
}

table ServiceRpcMessage {
    /// RPC: Call/Message/Request identifier.
    call_id: uint32;
    /// RPC: Message payload.
    payload: Payload;

    /// Identifier: Target ECU/Runnable for this Service RPC.
    ecu_name: string;
    /// Identifier: Target ECU for this Service RPC.
    ecu_id:uint32;
    /// Identifier: Target Runnable for this Service RPC.
    swc_id:uint32;
    /// Identifier: Frame ID related to _this_ Service RPC message if it
    ///  is transmitted on a bus (CAN, FlexRay, IP etc).
    frame_id: uint32;

    /// Metadata: Node UID of the Simulation (or System) node which is sending
    ///  this stream object. Used by a Node to detect incoming stream objects
    ///  which the Node had previously sent (i.e. an echo from the underlying
    ///  implementation of the stream transport).
    node_uid:uint32;

    /// Metadata: Message timestamp in simulation time.
    simulation_time: double;
    /// Metadata: UTC timestamp (i.e. wall clock).
    utc_time: uint64;
}

rpc_service ServiceRpc {
    Invoke(InvokeCall): InvokeReturn;
}

root_type ServiceRpcMessage;
file_identifier "DSRP";
